### SIGN UP
POST http://localhost:3006/auth/signup
Content-Type: application/json

{
  "username": "SomeDude2",
  "password": "StrongPassword2"
}

### SIGN IN

POST http://localhost:3006/auth/signin
Content-Type: application/json

 {
  "username": "SomeDude2",
  "password": "StrongPassword2"
 }  