### SIGN UP
POST http://localhost:3006/auth/signup
Content-Type: application/json

{
  "username": "SomeDude",
  "password": "StrongPassword1"
}

### SIGN IN

POST http://localhost:3006/auth/signin
Content-Type: application/json

 {
  "username": "SomeDude",
  "password": "StrongPassword1"
 }