GET http://localhost:3006/tasks
Content-Type: application/json

### GET ALL 

GET http://localhost:3006/tasks?status=DONE
Content-Type: application/json

### CREATE A TASK
POST http://localhost:3006/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6e30sImlhdCI6MTYxMDk0MzU5NiwiZXhwIjoxNjEwOTQ3MTk2fQ.t0wkpiAf3de9eHMoYDwseL_A8OQl3JiE1qkfvMiGuaw

{
  "title": "Buy something to eat 1",
  "description": "Cause im hungry 1"
}

### GET BY ID
GET http://localhost:3006/tasks/69ea4c97-745d-47a3-bc51-2f75b36879b9

### DELETE BY ID

DELETE  http://localhost:3006/tasks/9f9b9059-488f-4191-a0bc-b03e1ab3b8f5


### UPDATE TASK
PATCH http://localhost:3006/tasks/69ea4c97-745d-47a3-bc51-2f75b36879b9/status
Content-Type: application/json

{
  "status": "DONE"
}

